import type { Metadata } from "next";
import "./globals.css";
export const metadata: Metadata = {
  title: "Model-Merge",
  description: "Generated by create next app",
};
//My imports
import { ThemeProvider } from "@/components/ui/theme-provider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        {children}
      </ThemeProvider>
        </body>
    </html>
  );
}
